security:
  oauth2:
    client:
      clientId: 366621216993-3k48mg061f6ijnc3e09ercocs336c6im.apps.googleusercontent.com
      clientSecret: IJcaB38gthYeVqAZ3I7cfbPM
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      clientAuthenticationScheme: form
      scope:
        - openid
        - email
        - profile
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
      preferTokenInfo: true